ACSLXTREME_SETUP = C:\acslX\setup.in
AXLITEPATH = C:\acslX
MODEL_NAME = PF336A~1
MODEL_DIR = C:\acslX\PFOA\Project 1
TARGET_FULL = PFOA Adult Human 06262015 - loaded dw 3.55.dll
MODEL_RRR_FULL = PFOA Adult Human 06262015 - loaded dw 3.55.rrr
include C:\acslX\makedefs
