<optstats type="sensitiv anal object">
  <runoptions mscriptpre="pfoa adult human - initial parameter values.m" plotresults="True" />
  <coefficients>
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="bw" delta="0.8" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mkc" delta="4.4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mlc" delta="0.000257" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qcc" delta="0.125" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qlc" delta="0.0025" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qkc" delta="0.00175" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="htc" delta="0.0044" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vplasc" delta="0.000428" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vlc" delta="0.00026" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vkc" delta="4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vfilc" delta="4E-06" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vptcc" delta="1.35E-06" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mw" delta="4.1407" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="free" delta="0.0002" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vmax_baso_invitro" delta="4.392" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="km_baso" delta="201" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vmax_apical_invitro" delta="93" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="km_apical" delta="775" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="rafbaso" delta="0.000136" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="rafapi" delta="0.000136" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="protein" delta="2E-08" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="gfrc" delta="0.2419" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pl" delta="0.0103" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pk" delta="0.0117" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pr" delta="0.0011" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kdif" delta="1E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kabsc" delta="0.0212" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kunabsc" delta="7.06E-07" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="gec" delta="0.035" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="k0c" delta="0.01" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="keffluxc" delta="0.0249" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kbilec" delta="4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kurinec" delta="0.016" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="exposeddw" delta="15" normaltorespvar="True" normaltoparam="True" datacollectiontype="FinalValue" />
  </coefficients>
</optstats>