% M file automatically generated by acslXtreme on Friday, May 27, 2016 at 3:26:55 PM
% WARNING: DO NOT EDIT THE CONTENTS OF THIS FILE !!!
cd 'C:\acslX\PFOA\project 1'

% Execute pre-optimization script
use("pfoa adult human - initial parameter values")

% Sensitivity Analysis Run : C:\acslX\PFOA\project 1\PFOA Adult Human.m
% Uses simulation : PFOA Adult Human 06262015.dll

disp("");
disp("Performing Sensitivity Analysis Run 1 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["VKC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 4E-05
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = senscoef;

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 4E-05\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:vkc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 2 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["VFILC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 4E-06
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 4E-06\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:vfilc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 3 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["VPTCC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 1.35E-06
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 1.35E-06\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:vptcc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 4 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["MW"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 4.1407
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 4.1407\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:mw");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 5 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["FREE"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 5E-05
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 5E-05\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:free");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 6 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["VMAX_BASO_INVITRO"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 4.392
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 4.392\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:vmax_baso_invitro");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 7 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KM_BASO"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 201
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 201\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:km_baso");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 8 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["VMAX_APICAL_INVITRO"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 374
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 374\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:vmax_apical_invitro");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 9 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KM_APICAL"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 775
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 775\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:km_apical");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Runs 10 to 11 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA","CA"]
SvParameterNames = ["RAFBASO","K0C"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.01
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.01\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:rafbaso");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:k0c");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 3))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 12 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["RAFAPI"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 7E-05
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 7E-05\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:rafapi");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 13 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["PROTEIN"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 2E-08
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 2E-08\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:protein");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 14 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["GFRC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.2419
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.2419\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:gfrc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 15 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["PL"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0103
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0103\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:pl");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 16 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["PK"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0117
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0117\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:pk");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 17 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["PR"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0011
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0011\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:pr");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 18 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KDIF"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 1E-05
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 1E-05\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kdif");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 19 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KABSC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0212
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0212\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kabsc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 20 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KUNABSC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 7.06E-07
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 7.06E-07\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kunabsc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 21 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["GEC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.035
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.035\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:gec");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 22 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KBILEC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 1E-06
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 1E-06\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kbilec");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 23 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KVOID"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0006974
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0006974\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kvoid");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 24 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KEFFLUXC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.001
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.001\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:keffluxc");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 25 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["KURINEC"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.000715
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.000715\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:kurinec");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 26 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["EXPOSEDDW"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.0252
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.0252\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:exposeddw");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 27 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["DWTOTAL"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.012
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.012\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:dwtotal");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
disp("");
disp("Performing Sensitivity Analysis Run 28 of 39")
disp("---------------------------------------------------")

SvAlgorithm = 0
SvResponseNames = ["CA"]
SvParameterNames = ["INGEST"]
SvNormalizeToRespVar = 1
SvNormalizeToParam = 1
SvDelta = 0.00096
senscoef = sense(SvAlgorithm, SvResponseNames, SvParameterNames, SvNormalizeToRespVar, SvNormalizeToParam, SvDelta)
OpResults = [OpResults senscoef];

disp("-------------------------------")
set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(senscoef);
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Sensitivity Analysis Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Friday, May 27, 2016 at 3:26:55 PM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1 C:\\acslX\\PFOA\\project 1\\PFOA Adult Human.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 ForwardDifference\par ");
uitext = strcat(uitext, "\cf2 Delta:\tab\tab\cf1 0.00096\par ");
uitext = strcat(uitext, "\cf2 Normalize to Resp Var:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf2 Normalize to Param:\tab\tab\cf1 1\par ");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\cf0\fs22 Time for the final values: ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 1))));
uitext = strcat(uitext, "\cf0\fs22\par\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx2710 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5210 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Coefficient\cell");
uitext = strcat(uitext, "   Value\cell\row");
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx2710");
uitext = strcat(uitext, "\cellx2710");
uitext = strcat(uitext, "\cellx5210");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, "ca:ingest");
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", senscoef(nr, 2))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);
