% M file automatically generated by acslXtreme on Saturday, July 11, 2015 at 11:51:30 AM
% WARNING: DO NOT EDIT THE CONTENTS OF THIS FILE !!!
cd 'C:\Program Files (x86)\AEgis Technologies\acslX\PFOA\Project 1'

% Execute pre-optimization script
use("pfoa adult human - initial parameter values")

% Parameter Estimation Run : C:\Program Files (x86)\AEgis Technologies\acslX\PFOA\Project 1\PFOA Adult Human - Optimization.m
% Uses simulation : PFOA Adult Human 06262015.dll
disp("-------------------------------")

OpAdjustable = ["K0C", ...
"KABSC", ...
"KUNABSC", ...
"KBILEC", ...
"KEFFLUXC", ...
"KURINEC", ...
"RAFAPI", ...
"RAFBASO"]
OpStartValues = [1, ...
2.12, ...
7.06E-05, ...
0.004, ...
2.49, ...
1.6, ...
0.01356, ...
0.01356]
OpConstrained = ["K0C", ...
"KABSC", ...
"KUNABSC", ...
"KBILEC", ...
"KEFFLUXC", ...
"KURINEC", ...
"RAFAPI", ...
"RAFBASO"]
OpConstraints = [0, -1; ...
0, -1; ...
0, -1; ...
0, -1; ...
0, -1; ...
0, -1; ...
0, -1; ...
0, -1]

OpAlgorithm = 0
OpNMValues = [1E-05, 1E-05, 0.2, 1, 2, 0.5, 0.5, 10000];

OpTargetNames = [ ...
"CA" ]

OpErrModel = [ ...
1 0 ]

load @File='C:\Program Files (x86)\AEgis Technologies\acslX\PFOA\Project 1\bartell_data__for_optimizationm.csv' @Format='Ascii' @Separator='Comma'

OpData = [...
bartell_data__for_optimizationm( : , 1) bartell_data__for_optimizationm( : , 2) ]

OpDescriptors = [ ...
 ]

OpExperiments = [ ...
 ]

OpNumEval = [];
OpFinal = [];
OpOptimum = [];
OpInitial = [];
OpSecs = [];
OpInform = [];
OpHetParms = [];
OpHessian = [];

[OpOptimum, OpFinal, OpInitial, OpNumEval, OpSecs, OpInform, OpHetParms, OpHessian] = fitmult(OpTargetNames, OpErrModel, OpData, OpAlgorithm, OpAdjustable, OpStartValues, OpConstrained, OpConstraints, OpDescriptors, OpExperiments)
disp("-------------------------------")
OpVarCovar = varcovar(OpHessian)
OpCorrelation = correl(OpVarCovar)
OpParmStdDev = parmstd(OpVarCovar)

% Plot the fitted variables and observed data
start @NoCallback
plotHandle = plot( _t, _ca, ...
bartell_data__for_optimizationm( : , 1), bartell_data__for_optimizationm( : , 2), '*', 'pe_ca_1.aps');

set @Preference = NoBackSlashEscapes
uiHandle = uifigure;
rtbHandle = uicontrol(uiHandle, "RichTextBox");
uiset(uiHandle, rtbHandle, "Dock", "Fill");
uiset(uiHandle, rtbHandle, "ReadOnly", 1);
uiset(uiHandle, rtbHandle, "WordWrap", 0);
uiset(uiHandle, rtbHandle, "BackColor", "White");
[nr, nc] = size(OpFinal);
nr = nc;
nc = 2;
uitext = "";
uitext = strcat(uitext, "{\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fprq2\fcharset0 Arial;}{\f1\fswiss\fcharset0 Arial;}} ");
uitext = strcat(uitext, "{\colortbl ;\red51\green51\blue153;\red0\green0\blue0;\red255\green0\blue0;} ");
uitext = strcat(uitext, "\viewkind4\uc1\pard\li270\cf1\f0\fs28\par ");
uitext = strcat(uitext, "Parameter Estimation Results\par ");
uitext = strcat(uitext, "\cf0\fs22 ____________________________________________________________\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\fs24 Date:\tab\tab\cf1 Saturday, July 11, 2015 at 11:51:30 AM\tab\cf0\par ");
uitext = strcat(uitext, "Script File:\tab\tab\cf1C:\\Program Files (x86)\\AEgis Technologies\\acslX\\PFOA\\Project 1\\PFOA Adult Human - Optimization.m\par ");
uitext = strcat(uitext, "\cf2 Simulation DLL\cf0 : \tab\cf1 PFOA Adult Human 06262015.dll\par ");
uitext = strcat(uitext, "\par\cf2 Algorithm:\tab\tab\cf1 NelderMead\par ");
uitext = strcat(uitext, "\cf2 Initial LLF Value:\tab\cf1 ");
uitext = strcat(uitext, txt2str(sprintf("%e", -OpInitial)));
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\cf2 Final LLF Value:\tab\cf1 ");
uitext = strcat(uitext, txt2str(sprintf("%e", -OpOptimum)));
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\cf2 Obj Fun Evals:\tab\cf1 ");
uitext = strcat(uitext, txt2str(sprintf("%ld", OpNumEval)));
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\cf2 Processing Time:\tab\cf1 ");
uitext = strcat(uitext, txt2str(sprintf("%ld", OpSecs)));
uitext = strcat(uitext, " seconds \par ");
uitext = strcat(uitext, "\cf2 Result:\tab\tab\cf1 ");
uitext = strcat(uitext, txt2str(sprintf("%ld", OpInform)));
uitext = strcat(uitext, "\par ");
if OpInform == -1
uitext = strcat(uitext, "\cf3\b\fs24\par Note: Parameter estimation failed to converge.\par ");
uitext = strcat(uitext, "The results reported below reflect the values of the parameters\par ");
uitext = strcat(uitext, "at the conclusion of the run, but not necessarily the optimal values.\cf2\b0\par ");
end
uitext = strcat(uitext, "\cf2\par Parameter Estimates: \par");
uitext = strcat(uitext, "\cf0\fs22\par ");
uitext = strcat(uitext, "\trowd\trgaph10\trleft210 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs\clbrdrr\brdrw30\brdrs \cellx3600 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx5600 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx7600 ");
uitext = strcat(uitext, "\clbrdrb\brdrw30\brdrs \cellx9600 ");
uitext = strcat(uitext, "\pard\intbl\b\fs20");
uitext = strcat(uitext, "   Parameter\cell");
uitext = strcat(uitext, "   Initial Value\cell");
uitext = strcat(uitext, "   Final Value\cell");
uitext = strcat(uitext, "   Std. Dev.\cell");
uitext = strcat(uitext, "\row ");
for ii = [1 : nr]
uitext = strcat(uitext, "\trowd\trgaph10");
uitext = strcat(uitext, "\trleft210\clbrdrr\brdrw30\brdrs \cellx3600");
uitext = strcat(uitext, "\cellx5600");
uitext = strcat(uitext, "\cellx7600");
uitext = strcat(uitext, "\cellx9600");
uitext = strcat(uitext, "\pard\intbl\b");
uitext = strcat(uitext, "   ");
uitext = strcat(uitext, txt2str(sprintf("%s", OpAdjustable(ii))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", OpStartValues(ii))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", OpFinal(ii))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "  \b0 ");
uitext = strcat(uitext, txt2str(sprintf("%e", OpParmStdDev(ii))));
uitext = strcat(uitext, "\cell");
uitext = strcat(uitext, "\row ");
end
uitext = strcat(uitext, "\pard\li270\fs22\par ");
uitext = strcat(uitext, "\par ");
uitext = strcat(uitext, "\cf2\fs24\par ");
uitext = strcat(uitext, "Note: Final values have been written to the following m-script file, in order to make them available for subsequent executions of the simulation: \par");
uitext = strcat(uitext, "\cf1 ");
uitext = strcat(uitext, "C:\\Program Files (x86)\\AEgis Technologies\\acslX\\PFOA\\Project 1\\PFOA Adult Human - Optimization-params.m\par\par ");
uitext = strcat(uitext, rtftable("Variance-Covariance Matrix:", OpAdjustable, ["" OpAdjustable], OpVarCovar));
uitext = strcat(uitext, rtftable("Correlation Matrix:", OpAdjustable, ["" OpAdjustable], OpCorrelation));
uitext = strcat(uitext, "\f1\fs20\par ");
uitext = strcat(uitext, "} ");
uiset(uiHandle, rtbHandle, "Rtf", uitext);

set @Preference = BackSlashEscapes
mscript = "% Automatically generated through parameter estimation script 'PFOA Adult Human - Optimization.m'";
mscript = strcat(mscript, "\r\n\r\n");
for ii = [1 : nr]
mscript = strcat(mscript, OpAdjustable(ii) + " = " + txt2str(sprintf("%e", OpFinal(ii))));
mscript = strcat(mscript, ";\r\n");
end
set @Preference = NoBackSlashEscapes
mScriptFileId = fopen('C:\Program Files (x86)\AEgis Technologies\acslX\PFOA\Project 1\PFOA Adult Human - Optimization-params.m', 'w');
fprintf(mScriptFileId, "%s", mscript);
fclose(mScriptFileId);
