ACSLXTREME_SETUP = C:\acslX\setup.in
AXLITEPATH = C:\acslX
MODEL_NAME = PFOAAD~1
MODEL_DIR = C:\acslX\PFOA\PFOA Adult Human - 07172015
TARGET_FULL = PFOA Adult Human 07172015.dll
MODEL_RRR_FULL = PFOA Adult Human 07172015.rrr
include C:\acslX\makedefs
