
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <string>
#include "AcslSimRuntimeAPI.h"

void zzinitialize(unsigned long);
void zzsimulation(unsigned long);
void zzderivative(unsigned long, unsigned long);

typedef struct 
{
double t;
double aiv;
double aog;
double ar_free;
double ar_bound;
double akb_bound;
double akb_free;
double adif;
double a_baso;
double aptc;
double a_apical;
double aefflux;
double afil;
double aurine;
double ast;
double aabsst;
double asi;
double aabssi;
double al_free;
double afeces;
double al_bound;
double aplas;
double z99999;
double z99997;
double z99995;
double z99993;
double z99991;
double z99989;
double z99987;
double z99985;
double z99983;
double z99981;
double z99979;
double z99977;
double z99975;
double z99973;
double z99971;
double z99969;
double z99967;
double z99961;
double z99965;
double z99963;
double z99959;
double z99998;
double z99996;
double z99994;
double z99992;
double z99990;
double z99988;
double z99986;
double z99984;
double z99982;
double z99980;
double z99978;
double z99976;
double z99974;
double z99972;
double z99970;
double z99968;
double z99966;
double z99960;
double z99964;
double z99962;
double z99958;
double tstart;
double bw;
double mkc;
double mlc;
double qcc;
double qlc;
double qkc;
double htc;
double vplasc;
double vlc;
double vkc;
double vfilc;
double vptcc;
double mw;
double free;
double vmax_baso_invitro;
double km_baso;
double vmax_apical_invitro;
double km_apical;
double rafbaso;
double rafapi;
double protein;
double gfrc;
double pl;
double pk;
double pr;
double kb;
double bmax;
double koff;
double kdif;
double kabs;
double kunabs;
double gec;
double k0c;
double keffluxc;
double kbilec;
double kurinec;
double odosec;
double ogtime;
double ivdosec;
double ivtime;
double qc;
double qk;
double ql;
double qr;
double qbal;
double vplas;
double vk;
double vkb;
double vfil;
double vl;
double vr;
double vptc;
double vbal;
double ml;
double mk;
double ptc;
double mptc;
double vmax_basoc;
double vmax_apicalc;
double vmax_baso;
double vmax_apical;
double kbile;
double kurine;
double kefflux;
double gfr;
double ge;
double k0;
double ivdose;
double ivr;
double ivon;
double odose;
double ogr;
double ogon;
double rr_free;
double ca;
double cvr;
double cr_free;
double rr_bound;
double cr_bound;
double rkb_bound;
double cvk;
double ckb_bound;
double rkb_free;
double rdif;
double ra_baso;
double ckb_free;
double cptc;
double rptc;
double ra_apical;
double raefflux;
double cfil;
double rfil;
double rurine;
double percentod_in_urine;
double rst;
double rabsst;
double rsi;
double rabssi;
double total_oral_uptake;
double rfeces;
double percentod_in_feces;
double rl_bound;
double cvl;
double cl_bound;
double rl_free;
double cl_free;
double cl;
double abile;
double amount_per_gram_liver;
double rplas;
double atissue;
double aloss;
double atotal;
double tstop;
double cint;
long ialg;
long nstp;
double maxt;
double mint;
bool zzierr;
bool zzstopflag;
bool zzrnfl;
long zznist;
long zznblk;
bool zzfrfl;
bool zzjefl;
long zzndst;
long zzicon;
bool zzicfl;
long zznavr;
long zzinstidx;
bool zzstepstop;
long nciout;
long cioitg;
bool cjvitg;
double cssitg;
bool dpsitg;
bool ecsitg;
bool fdeitg;
long mxoitg;
bool nrwitg;
bool nxeitg;
double tjnitg;
bool tsmitg;
bool weditg;
bool wesitg;
bool wnditg;
bool wxditg;
bool cieitg;
long ubwitg;
long lbwitg;
long omfitg;
long cmd;
long dis;
long ndbug;
long plt;
long prn;
long malprn;
long rrr;
long save;
double zzticg;

} SimImpl;
SimImpl zzsim = 
{
0.0,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
0.0,
0.3,
0.0084,
0.034,
14.0,
0.183,
0.141,
0.46,
0.0312,
0.035,
0.0084,
8.4e-4,
1.35e-4,
414.07,
0.006,
393.45,
37.7,
18861.8,
141,
0.01356,
0.01356,
2.0e-6,
62.1,
2.2,
1.05,
0.11,
1,
1,
1,
0.001,
0.3,
0.0001,
0.54,
1.0e-33,
10,
0.0075,
0.1,
1.0e-33,
0.01,
1.0,
0.01,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
24.0,
0.01,
5,
10,
1.0e9,
1.0e-9,
false,
false,
false,
2,
1,
false,
false,
0,
0,
false,
0,
0,
false,
1,
55555555,
true,
5.5555E+33,
true,
false,
false,
6,
false,
false,
0.2,
false,
true,
true,
false,
false,
true,
-1,
-1,
222,
4,
6,
0,
6,
9,
10,
8,
3,
0.0,

};

void AcslSimMain()
{

	AcslSimSetSystemInfo(226,// numSymbols
	21, // numOdeStates
	0, // numDaeStates
	0, // numDelayStates
	115,// numAlgebraicVars
	1, // numDerivativeSections
	0, // numDiscreteSections
	zzinitialize,
	zzsimulation,
	zzderivative,
	0);



#ifndef TRUE
  #define TRUE true
#endif
#ifndef FALSE
  #define FALSE false
#endif

AcslSimSetVariableDescriptor(1,"t",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_VARIABLE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(1,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(2,"aiv",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(2,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(3,"aog",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(3,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(4,"ar_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(4,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(5,"ar_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(5,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(6,"akb_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(6,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(7,"akb_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(7,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(8,"adif",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(8,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(9,"a_baso",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(9,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(10,"aptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(10,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(11,"a_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(11,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(12,"aefflux",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(12,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(13,"afil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(13,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(14,"aurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(14,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(15,"ast",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(15,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(16,"aabsst",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(16,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(17,"asi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(17,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(18,"aabssi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(18,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(19,"al_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(19,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(20,"afeces",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(20,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(21,"al_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(21,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(22,"aplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(22,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(23,"z99999",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(23,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(24,"z99997",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(24,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(25,"z99995",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(25,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(26,"z99993",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(26,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(27,"z99991",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(27,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(28,"z99989",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(28,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(29,"z99987",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(29,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(30,"z99985",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(30,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(31,"z99983",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(31,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(32,"z99981",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(32,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(33,"z99979",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(33,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(34,"z99977",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(34,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(35,"z99975",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(35,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(36,"z99973",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(36,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(37,"z99971",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(37,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(38,"z99969",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(38,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(39,"z99967",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(39,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(40,"z99961",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(40,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(41,"z99965",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(41,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(42,"z99963",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(42,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(43,"z99959",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(43,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(44,"z99998",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(44,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(45,"z99996",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(45,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(46,"z99994",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(46,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(47,"z99992",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(47,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(48,"z99990",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(48,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(49,"z99988",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(49,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(50,"z99986",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(50,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(51,"z99984",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(51,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(52,"z99982",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(52,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(53,"z99980",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(53,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(54,"z99978",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(54,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(55,"z99976",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(55,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(56,"z99974",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(56,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(57,"z99972",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(57,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(58,"z99970",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(58,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(59,"z99968",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(59,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(60,"z99966",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(60,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(61,"z99960",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(61,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(62,"z99964",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(62,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(63,"z99962",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(63,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(64,"z99958",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(64,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(65,"tstart",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(65,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(66,"bw",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(66,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(67,"mkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(67,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(68,"mlc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(68,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(69,"qcc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(69,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(70,"qlc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(70,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(71,"qkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(71,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(72,"htc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(72,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(73,"vplasc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(73,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(74,"vlc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(74,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(75,"vkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(75,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(76,"vfilc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(76,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(77,"vptcc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(77,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(78,"mw",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(78,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(79,"free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(79,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(80,"vmax_baso_invitro",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(80,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(81,"km_baso",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(81,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(82,"vmax_apical_invitro",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(82,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(83,"km_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(83,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(84,"rafbaso",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(84,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(85,"rafapi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(85,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(86,"protein",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(86,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(87,"gfrc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(87,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(88,"pl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(88,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(89,"pk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(89,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(90,"pr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(90,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(91,"kb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(91,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(92,"bmax",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(92,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(93,"koff",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(93,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(94,"kdif",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(94,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(95,"kabs",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(95,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(96,"kunabs",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(96,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(97,"gec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(97,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(98,"k0c",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(98,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(99,"keffluxc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(99,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(100,"kbilec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(100,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(101,"kurinec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(101,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(102,"odosec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(102,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(103,"ogtime",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(103,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(104,"ivdosec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(104,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(105,"ivtime",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(105,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(106,"qc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(106,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(107,"qk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(107,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(108,"ql",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(108,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(109,"qr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(109,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(110,"qbal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(110,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(111,"vplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(111,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(112,"vk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(112,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(113,"vkb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(113,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(114,"vfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(114,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(115,"vl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(115,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(116,"vr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(116,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(117,"vptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(117,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(118,"vbal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(118,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(119,"ml",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(119,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(120,"mk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(120,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(121,"ptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(121,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(122,"mptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(122,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(123,"vmax_basoc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(123,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(124,"vmax_apicalc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(124,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(125,"vmax_baso",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(125,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(126,"vmax_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(126,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(127,"kbile",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(127,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(128,"kurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(128,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(129,"kefflux",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(129,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(130,"gfr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(130,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(131,"ge",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(131,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(132,"k0",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(132,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(133,"ivdose",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(133,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(134,"ivr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(134,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(135,"ivon",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(135,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(136,"odose",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(136,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(137,"ogr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(137,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(138,"ogon",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(138,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(139,"rr_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(139,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(140,"ca",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(140,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(141,"cvr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(141,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(142,"cr_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(142,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(143,"rr_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(143,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(144,"cr_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(144,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(145,"rkb_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(145,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(146,"cvk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(146,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(147,"ckb_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(147,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(148,"rkb_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(148,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(149,"rdif",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(149,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(150,"ra_baso",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(150,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(151,"ckb_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(151,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(152,"cptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(152,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(153,"rptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(153,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(154,"ra_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(154,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(155,"raefflux",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(155,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(156,"cfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(156,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(157,"rfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(157,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(158,"rurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(158,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(159,"percentod_in_urine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(159,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(160,"rst",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(160,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(161,"rabsst",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(161,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(162,"rsi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(162,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(163,"rabssi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(163,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(164,"total_oral_uptake",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(164,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(165,"rfeces",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(165,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(166,"percentod_in_feces",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(166,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(167,"rl_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(167,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(168,"cvl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(168,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(169,"cl_bound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(169,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(170,"rl_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(170,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(171,"cl_free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(171,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(172,"cl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(172,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(173,"abile",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(173,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(174,"amount_per_gram_liver",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(174,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(175,"rplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(175,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(176,"atissue",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(176,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(177,"aloss",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(177,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(178,"atotal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(178,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(179,"tstop",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(179,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(180,"cint",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_CINTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(180,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(181,"ialg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ALGORITHM,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(181,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(182,"nstp",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_NSTEPS,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(182,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(183,"maxt",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_MAXTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(183,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(184,"mint",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_MINTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(184,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(185,"zzierr",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ERRTAG,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(185,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(186,"zzstopflag",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(186,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(187,"zzrnfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(187,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(188,"zznist",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(188,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(189,"zznblk",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(189,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(190,"zzfrfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(190,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(191,"zzjefl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(191,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(192,"zzndst",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(192,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(193,"zzicon",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(193,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(194,"zzicfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(194,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(195,"zznavr",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(195,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(196,"zzinstidx",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(196,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(197,"zzstepstop",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(197,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(198,"nciout",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(198,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(199,"cioitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(199,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(200,"cjvitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(200,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(201,"cssitg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(201,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(202,"dpsitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(202,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(203,"ecsitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(203,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(204,"fdeitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(204,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(205,"mxoitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(205,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(206,"nrwitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(206,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(207,"nxeitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(207,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(208,"tjnitg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(208,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(209,"tsmitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(209,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(210,"weditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(210,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(211,"wesitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(211,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(212,"wnditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(212,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(213,"wxditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(213,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(214,"cieitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(214,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(215,"ubwitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(215,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(216,"lbwitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(216,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(217,"omfitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(217,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(218,"cmd",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(218,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(219,"dis",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(219,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(220,"ndbug",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(220,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(221,"plt",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(221,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(222,"prn",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(222,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(223,"malprn",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(223,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(224,"rrr",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(224,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(225,"save",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(225,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(226,"zzticg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_VARIABLE_INIT,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(226,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

}

//******************************************************************************
void zzinitialize(unsigned long handle)
//******************************************************************************

{
AcslSimSetVariablePointer(handle,1,&zzsim.t);
AcslSimSetVariablePointer(handle,2,&zzsim.aiv);
AcslSimSetVariablePointer(handle,3,&zzsim.aog);
AcslSimSetVariablePointer(handle,4,&zzsim.ar_free);
AcslSimSetVariablePointer(handle,5,&zzsim.ar_bound);
AcslSimSetVariablePointer(handle,6,&zzsim.akb_bound);
AcslSimSetVariablePointer(handle,7,&zzsim.akb_free);
AcslSimSetVariablePointer(handle,8,&zzsim.adif);
AcslSimSetVariablePointer(handle,9,&zzsim.a_baso);
AcslSimSetVariablePointer(handle,10,&zzsim.aptc);
AcslSimSetVariablePointer(handle,11,&zzsim.a_apical);
AcslSimSetVariablePointer(handle,12,&zzsim.aefflux);
AcslSimSetVariablePointer(handle,13,&zzsim.afil);
AcslSimSetVariablePointer(handle,14,&zzsim.aurine);
AcslSimSetVariablePointer(handle,15,&zzsim.ast);
AcslSimSetVariablePointer(handle,16,&zzsim.aabsst);
AcslSimSetVariablePointer(handle,17,&zzsim.asi);
AcslSimSetVariablePointer(handle,18,&zzsim.aabssi);
AcslSimSetVariablePointer(handle,19,&zzsim.al_free);
AcslSimSetVariablePointer(handle,20,&zzsim.afeces);
AcslSimSetVariablePointer(handle,21,&zzsim.al_bound);
AcslSimSetVariablePointer(handle,22,&zzsim.aplas);
AcslSimSetVariablePointer(handle,23,&zzsim.z99999);
AcslSimSetVariablePointer(handle,24,&zzsim.z99997);
AcslSimSetVariablePointer(handle,25,&zzsim.z99995);
AcslSimSetVariablePointer(handle,26,&zzsim.z99993);
AcslSimSetVariablePointer(handle,27,&zzsim.z99991);
AcslSimSetVariablePointer(handle,28,&zzsim.z99989);
AcslSimSetVariablePointer(handle,29,&zzsim.z99987);
AcslSimSetVariablePointer(handle,30,&zzsim.z99985);
AcslSimSetVariablePointer(handle,31,&zzsim.z99983);
AcslSimSetVariablePointer(handle,32,&zzsim.z99981);
AcslSimSetVariablePointer(handle,33,&zzsim.z99979);
AcslSimSetVariablePointer(handle,34,&zzsim.z99977);
AcslSimSetVariablePointer(handle,35,&zzsim.z99975);
AcslSimSetVariablePointer(handle,36,&zzsim.z99973);
AcslSimSetVariablePointer(handle,37,&zzsim.z99971);
AcslSimSetVariablePointer(handle,38,&zzsim.z99969);
AcslSimSetVariablePointer(handle,39,&zzsim.z99967);
AcslSimSetVariablePointer(handle,40,&zzsim.z99961);
AcslSimSetVariablePointer(handle,41,&zzsim.z99965);
AcslSimSetVariablePointer(handle,42,&zzsim.z99963);
AcslSimSetVariablePointer(handle,43,&zzsim.z99959);
AcslSimSetVariablePointer(handle,44,&zzsim.z99998);
AcslSimSetVariablePointer(handle,45,&zzsim.z99996);
AcslSimSetVariablePointer(handle,46,&zzsim.z99994);
AcslSimSetVariablePointer(handle,47,&zzsim.z99992);
AcslSimSetVariablePointer(handle,48,&zzsim.z99990);
AcslSimSetVariablePointer(handle,49,&zzsim.z99988);
AcslSimSetVariablePointer(handle,50,&zzsim.z99986);
AcslSimSetVariablePointer(handle,51,&zzsim.z99984);
AcslSimSetVariablePointer(handle,52,&zzsim.z99982);
AcslSimSetVariablePointer(handle,53,&zzsim.z99980);
AcslSimSetVariablePointer(handle,54,&zzsim.z99978);
AcslSimSetVariablePointer(handle,55,&zzsim.z99976);
AcslSimSetVariablePointer(handle,56,&zzsim.z99974);
AcslSimSetVariablePointer(handle,57,&zzsim.z99972);
AcslSimSetVariablePointer(handle,58,&zzsim.z99970);
AcslSimSetVariablePointer(handle,59,&zzsim.z99968);
AcslSimSetVariablePointer(handle,60,&zzsim.z99966);
AcslSimSetVariablePointer(handle,61,&zzsim.z99960);
AcslSimSetVariablePointer(handle,62,&zzsim.z99964);
AcslSimSetVariablePointer(handle,63,&zzsim.z99962);
AcslSimSetVariablePointer(handle,64,&zzsim.z99958);
AcslSimSetVariablePointer(handle,65,&zzsim.tstart);
AcslSimSetVariablePointer(handle,66,&zzsim.bw);
AcslSimSetVariablePointer(handle,67,&zzsim.mkc);
AcslSimSetVariablePointer(handle,68,&zzsim.mlc);
AcslSimSetVariablePointer(handle,69,&zzsim.qcc);
AcslSimSetVariablePointer(handle,70,&zzsim.qlc);
AcslSimSetVariablePointer(handle,71,&zzsim.qkc);
AcslSimSetVariablePointer(handle,72,&zzsim.htc);
AcslSimSetVariablePointer(handle,73,&zzsim.vplasc);
AcslSimSetVariablePointer(handle,74,&zzsim.vlc);
AcslSimSetVariablePointer(handle,75,&zzsim.vkc);
AcslSimSetVariablePointer(handle,76,&zzsim.vfilc);
AcslSimSetVariablePointer(handle,77,&zzsim.vptcc);
AcslSimSetVariablePointer(handle,78,&zzsim.mw);
AcslSimSetVariablePointer(handle,79,&zzsim.free);
AcslSimSetVariablePointer(handle,80,&zzsim.vmax_baso_invitro);
AcslSimSetVariablePointer(handle,81,&zzsim.km_baso);
AcslSimSetVariablePointer(handle,82,&zzsim.vmax_apical_invitro);
AcslSimSetVariablePointer(handle,83,&zzsim.km_apical);
AcslSimSetVariablePointer(handle,84,&zzsim.rafbaso);
AcslSimSetVariablePointer(handle,85,&zzsim.rafapi);
AcslSimSetVariablePointer(handle,86,&zzsim.protein);
AcslSimSetVariablePointer(handle,87,&zzsim.gfrc);
AcslSimSetVariablePointer(handle,88,&zzsim.pl);
AcslSimSetVariablePointer(handle,89,&zzsim.pk);
AcslSimSetVariablePointer(handle,90,&zzsim.pr);
AcslSimSetVariablePointer(handle,91,&zzsim.kb);
AcslSimSetVariablePointer(handle,92,&zzsim.bmax);
AcslSimSetVariablePointer(handle,93,&zzsim.koff);
AcslSimSetVariablePointer(handle,94,&zzsim.kdif);
AcslSimSetVariablePointer(handle,95,&zzsim.kabs);
AcslSimSetVariablePointer(handle,96,&zzsim.kunabs);
AcslSimSetVariablePointer(handle,97,&zzsim.gec);
AcslSimSetVariablePointer(handle,98,&zzsim.k0c);
AcslSimSetVariablePointer(handle,99,&zzsim.keffluxc);
AcslSimSetVariablePointer(handle,100,&zzsim.kbilec);
AcslSimSetVariablePointer(handle,101,&zzsim.kurinec);
AcslSimSetVariablePointer(handle,102,&zzsim.odosec);
AcslSimSetVariablePointer(handle,103,&zzsim.ogtime);
AcslSimSetVariablePointer(handle,104,&zzsim.ivdosec);
AcslSimSetVariablePointer(handle,105,&zzsim.ivtime);
AcslSimSetVariablePointer(handle,106,&zzsim.qc);
AcslSimSetVariablePointer(handle,107,&zzsim.qk);
AcslSimSetVariablePointer(handle,108,&zzsim.ql);
AcslSimSetVariablePointer(handle,109,&zzsim.qr);
AcslSimSetVariablePointer(handle,110,&zzsim.qbal);
AcslSimSetVariablePointer(handle,111,&zzsim.vplas);
AcslSimSetVariablePointer(handle,112,&zzsim.vk);
AcslSimSetVariablePointer(handle,113,&zzsim.vkb);
AcslSimSetVariablePointer(handle,114,&zzsim.vfil);
AcslSimSetVariablePointer(handle,115,&zzsim.vl);
AcslSimSetVariablePointer(handle,116,&zzsim.vr);
AcslSimSetVariablePointer(handle,117,&zzsim.vptc);
AcslSimSetVariablePointer(handle,118,&zzsim.vbal);
AcslSimSetVariablePointer(handle,119,&zzsim.ml);
AcslSimSetVariablePointer(handle,120,&zzsim.mk);
AcslSimSetVariablePointer(handle,121,&zzsim.ptc);
AcslSimSetVariablePointer(handle,122,&zzsim.mptc);
AcslSimSetVariablePointer(handle,123,&zzsim.vmax_basoc);
AcslSimSetVariablePointer(handle,124,&zzsim.vmax_apicalc);
AcslSimSetVariablePointer(handle,125,&zzsim.vmax_baso);
AcslSimSetVariablePointer(handle,126,&zzsim.vmax_apical);
AcslSimSetVariablePointer(handle,127,&zzsim.kbile);
AcslSimSetVariablePointer(handle,128,&zzsim.kurine);
AcslSimSetVariablePointer(handle,129,&zzsim.kefflux);
AcslSimSetVariablePointer(handle,130,&zzsim.gfr);
AcslSimSetVariablePointer(handle,131,&zzsim.ge);
AcslSimSetVariablePointer(handle,132,&zzsim.k0);
AcslSimSetVariablePointer(handle,133,&zzsim.ivdose);
AcslSimSetVariablePointer(handle,134,&zzsim.ivr);
AcslSimSetVariablePointer(handle,135,&zzsim.ivon);
AcslSimSetVariablePointer(handle,136,&zzsim.odose);
AcslSimSetVariablePointer(handle,137,&zzsim.ogr);
AcslSimSetVariablePointer(handle,138,&zzsim.ogon);
AcslSimSetVariablePointer(handle,139,&zzsim.rr_free);
AcslSimSetVariablePointer(handle,140,&zzsim.ca);
AcslSimSetVariablePointer(handle,141,&zzsim.cvr);
AcslSimSetVariablePointer(handle,142,&zzsim.cr_free);
AcslSimSetVariablePointer(handle,143,&zzsim.rr_bound);
AcslSimSetVariablePointer(handle,144,&zzsim.cr_bound);
AcslSimSetVariablePointer(handle,145,&zzsim.rkb_bound);
AcslSimSetVariablePointer(handle,146,&zzsim.cvk);
AcslSimSetVariablePointer(handle,147,&zzsim.ckb_bound);
AcslSimSetVariablePointer(handle,148,&zzsim.rkb_free);
AcslSimSetVariablePointer(handle,149,&zzsim.rdif);
AcslSimSetVariablePointer(handle,150,&zzsim.ra_baso);
AcslSimSetVariablePointer(handle,151,&zzsim.ckb_free);
AcslSimSetVariablePointer(handle,152,&zzsim.cptc);
AcslSimSetVariablePointer(handle,153,&zzsim.rptc);
AcslSimSetVariablePointer(handle,154,&zzsim.ra_apical);
AcslSimSetVariablePointer(handle,155,&zzsim.raefflux);
AcslSimSetVariablePointer(handle,156,&zzsim.cfil);
AcslSimSetVariablePointer(handle,157,&zzsim.rfil);
AcslSimSetVariablePointer(handle,158,&zzsim.rurine);
AcslSimSetVariablePointer(handle,159,&zzsim.percentod_in_urine);
AcslSimSetVariablePointer(handle,160,&zzsim.rst);
AcslSimSetVariablePointer(handle,161,&zzsim.rabsst);
AcslSimSetVariablePointer(handle,162,&zzsim.rsi);
AcslSimSetVariablePointer(handle,163,&zzsim.rabssi);
AcslSimSetVariablePointer(handle,164,&zzsim.total_oral_uptake);
AcslSimSetVariablePointer(handle,165,&zzsim.rfeces);
AcslSimSetVariablePointer(handle,166,&zzsim.percentod_in_feces);
AcslSimSetVariablePointer(handle,167,&zzsim.rl_bound);
AcslSimSetVariablePointer(handle,168,&zzsim.cvl);
AcslSimSetVariablePointer(handle,169,&zzsim.cl_bound);
AcslSimSetVariablePointer(handle,170,&zzsim.rl_free);
AcslSimSetVariablePointer(handle,171,&zzsim.cl_free);
AcslSimSetVariablePointer(handle,172,&zzsim.cl);
AcslSimSetVariablePointer(handle,173,&zzsim.abile);
AcslSimSetVariablePointer(handle,174,&zzsim.amount_per_gram_liver);
AcslSimSetVariablePointer(handle,175,&zzsim.rplas);
AcslSimSetVariablePointer(handle,176,&zzsim.atissue);
AcslSimSetVariablePointer(handle,177,&zzsim.aloss);
AcslSimSetVariablePointer(handle,178,&zzsim.atotal);
AcslSimSetVariablePointer(handle,179,&zzsim.tstop);
AcslSimSetVariablePointer(handle,180,&zzsim.cint);
AcslSimSetVariablePointer(handle,181,&zzsim.ialg);
AcslSimSetVariablePointer(handle,182,&zzsim.nstp);
AcslSimSetVariablePointer(handle,183,&zzsim.maxt);
AcslSimSetVariablePointer(handle,184,&zzsim.mint);
AcslSimSetVariablePointer(handle,185,&zzsim.zzierr);
AcslSimSetVariablePointer(handle,186,&zzsim.zzstopflag);
AcslSimSetVariablePointer(handle,187,&zzsim.zzrnfl);
AcslSimSetVariablePointer(handle,188,&zzsim.zznist);
AcslSimSetVariablePointer(handle,189,&zzsim.zznblk);
AcslSimSetVariablePointer(handle,190,&zzsim.zzfrfl);
AcslSimSetVariablePointer(handle,191,&zzsim.zzjefl);
AcslSimSetVariablePointer(handle,192,&zzsim.zzndst);
AcslSimSetVariablePointer(handle,193,&zzsim.zzicon);
AcslSimSetVariablePointer(handle,194,&zzsim.zzicfl);
AcslSimSetVariablePointer(handle,195,&zzsim.zznavr);
AcslSimSetVariablePointer(handle,196,&zzsim.zzinstidx);
AcslSimSetVariablePointer(handle,197,&zzsim.zzstepstop);
AcslSimSetVariablePointer(handle,198,&zzsim.nciout);
AcslSimSetVariablePointer(handle,199,&zzsim.cioitg);
AcslSimSetVariablePointer(handle,200,&zzsim.cjvitg);
AcslSimSetVariablePointer(handle,201,&zzsim.cssitg);
AcslSimSetVariablePointer(handle,202,&zzsim.dpsitg);
AcslSimSetVariablePointer(handle,203,&zzsim.ecsitg);
AcslSimSetVariablePointer(handle,204,&zzsim.fdeitg);
AcslSimSetVariablePointer(handle,205,&zzsim.mxoitg);
AcslSimSetVariablePointer(handle,206,&zzsim.nrwitg);
AcslSimSetVariablePointer(handle,207,&zzsim.nxeitg);
AcslSimSetVariablePointer(handle,208,&zzsim.tjnitg);
AcslSimSetVariablePointer(handle,209,&zzsim.tsmitg);
AcslSimSetVariablePointer(handle,210,&zzsim.weditg);
AcslSimSetVariablePointer(handle,211,&zzsim.wesitg);
AcslSimSetVariablePointer(handle,212,&zzsim.wnditg);
AcslSimSetVariablePointer(handle,213,&zzsim.wxditg);
AcslSimSetVariablePointer(handle,214,&zzsim.cieitg);
AcslSimSetVariablePointer(handle,215,&zzsim.ubwitg);
AcslSimSetVariablePointer(handle,216,&zzsim.lbwitg);
AcslSimSetVariablePointer(handle,217,&zzsim.omfitg);
AcslSimSetVariablePointer(handle,218,&zzsim.cmd);
AcslSimSetVariablePointer(handle,219,&zzsim.dis);
AcslSimSetVariablePointer(handle,220,&zzsim.ndbug);
AcslSimSetVariablePointer(handle,221,&zzsim.plt);
AcslSimSetVariablePointer(handle,222,&zzsim.prn);
AcslSimSetVariablePointer(handle,223,&zzsim.malprn);
AcslSimSetVariablePointer(handle,224,&zzsim.rrr);
AcslSimSetVariablePointer(handle,225,&zzsim.save);
AcslSimSetVariablePointer(handle,226,&zzsim.zzticg);

zzsim.zzinstidx = handle;
}

//******************************************************************************
void zzsimulation(unsigned long handle)
//******************************************************************************

{
   if(zzsim.zzicon == false)
   {
      zznits(handle, "");




 
      zzrset(handle);
   }

   while(zzsim.zzstopflag == false && zzsim.zzstepstop == false)
   {



if((zzsim.t >= zzsim.tstop))
{

zztrmt(zzsim.zzinstidx,"checked on communication interval: REACHED TSTOP")
;

}

   

      AcslSimIntegrate(handle);
   }

   if(zzsim.zzstepstop == false)
   {
   


   

   }
}

//******************************************************************************
void zzderivative(unsigned long handle, unsigned long section)
//******************************************************************************

{

switch(section) 
{
   case 0: /* Initial */


			
		      
   break;
   case 1: /* Terminal */


			
		   
   break;
case 2: /* Dynamic */


			
		   
   break;
case 3: /* Left over code, executed once */


  
   
   break;


   /* Derivative */
			

case 500:


zzsim.ivdose = (zzsim.ivdosec * zzsim.bw);


zzsim.ivon = rsw((zzsim.t >= zzsim.ivtime),0.,1.);


zzsim.ivr = ((zzsim.ivon * zzsim.ivdose) / zzsim.ivtime);


zzsim.z99999 = zzsim.ivr;


zzsim.odose = (zzsim.odosec * zzsim.bw);


zzsim.ogon = rsw((zzsim.t >= zzsim.ogtime),0.,1.);


zzsim.ogr = ((zzsim.ogon * zzsim.odose) / zzsim.ogtime);


zzsim.z99997 = zzsim.ogr;


zzsim.qc = ((zzsim.qcc * ( pow ( zzsim.bw , 0.75 ) )) * (1 - zzsim.htc));


zzsim.qk = (zzsim.qkc * zzsim.qc);


zzsim.ql = (zzsim.qlc * zzsim.qc);


zzsim.qr = ((zzsim.qc - zzsim.qk) - zzsim.ql);


zzsim.vplas = (zzsim.vplasc * zzsim.bw);


zzsim.ca = (zzsim.aplas / zzsim.vplas);


zzsim.vk = (zzsim.vkc * zzsim.bw);


zzsim.vkb = (zzsim.vk * 0.16);


zzsim.vfil = (zzsim.vfilc * zzsim.bw);


zzsim.vl = (zzsim.vlc * zzsim.bw);


zzsim.mk = ((zzsim.mkc * zzsim.bw) * 1000);


zzsim.vptc = (zzsim.mk * zzsim.vptcc);


zzsim.vr = (((((((0.84 * zzsim.bw) - zzsim.vplas) - zzsim.vkb) - zzsim.vptc) - zzsim.vfil) - zzsim.vl) - zzsim.vk);


zzsim.cr_free = (zzsim.ar_free / zzsim.vr);


zzsim.cr_bound = (zzsim.ar_bound / zzsim.vr);


zzsim.cvr = ((zzsim.cr_free / zzsim.pr) + zzsim.cr_bound);


zzsim.rr_free = ((zzsim.qr * (zzsim.ca - zzsim.cvr)) * zzsim.free);


zzsim.z99995 = zzsim.rr_free;


zzsim.rr_bound = ((zzsim.qr * (zzsim.ca - zzsim.cvr)) * (1 - zzsim.free));


zzsim.z99993 = zzsim.rr_bound;


zzsim.ckb_bound = (zzsim.akb_bound / zzsim.vkb);


zzsim.ckb_free = (zzsim.akb_free / zzsim.vkb);


zzsim.cvk = ((zzsim.ckb_free / zzsim.pk) + zzsim.ckb_bound);


zzsim.rkb_bound = ((zzsim.qk * (zzsim.ca - zzsim.cvk)) * (1 - zzsim.free));


zzsim.z99991 = zzsim.rkb_bound;


zzsim.gfr = (zzsim.gfrc * (zzsim.mk / 1000));


zzsim.cptc = (zzsim.aptc / zzsim.vptc);


zzsim.rdif = (zzsim.kdif * (zzsim.ckb_free - zzsim.cptc));


zzsim.ptc = (zzsim.mk * 6e7);


zzsim.vmax_basoc = ((((((zzsim.vmax_baso_invitro * zzsim.rafbaso) * zzsim.ptc) * zzsim.protein) * 60) * (zzsim.mw / 1e12)) * 1000);


zzsim.vmax_baso = (zzsim.vmax_basoc * ( pow ( zzsim.bw , 0.75 ) ));


zzsim.ra_baso = ((zzsim.vmax_baso * zzsim.ckb_free) / (zzsim.km_baso + zzsim.ckb_free));


zzsim.rkb_free = (((((zzsim.qk * (zzsim.ca - zzsim.cvk)) * zzsim.free) - ((zzsim.ca * zzsim.gfr) * zzsim.free)) - zzsim.rdif) - zzsim.ra_baso);


zzsim.z99989 = zzsim.rkb_free;


zzsim.z99987 = zzsim.rdif;


zzsim.z99985 = zzsim.ra_baso;


zzsim.vmax_apicalc = ((((((zzsim.vmax_apical_invitro * zzsim.rafapi) * zzsim.ptc) * zzsim.protein) * 60) * (zzsim.mw / 1e12)) * 1000);


zzsim.vmax_apical = (zzsim.vmax_apicalc * ( pow ( zzsim.bw , 0.75 ) ));


zzsim.cfil = (zzsim.afil / zzsim.vfil);


zzsim.ra_apical = ((zzsim.vmax_apical * zzsim.cfil) / (zzsim.km_apical + zzsim.cfil));


zzsim.kefflux = (zzsim.keffluxc * ( pow ( zzsim.bw , 0.75 ) ));


zzsim.raefflux = (zzsim.kefflux * zzsim.aptc);


zzsim.rptc = (((zzsim.rdif + zzsim.ra_apical) + zzsim.ra_baso) - zzsim.raefflux);


zzsim.z99983 = zzsim.rptc;


zzsim.z99981 = zzsim.ra_apical;


zzsim.z99979 = zzsim.raefflux;


zzsim.kurine = (zzsim.kurinec * ( pow ( zzsim.bw , -(0.25) ) ));


zzsim.rfil = ((((zzsim.ca * zzsim.gfr) * zzsim.free) - zzsim.ra_apical) - (zzsim.afil * zzsim.kurine));


zzsim.z99977 = zzsim.rfil;


zzsim.rurine = (zzsim.kurine * zzsim.afil);


zzsim.z99975 = zzsim.rurine;


zzsim.ge = (zzsim.gec / ( pow ( zzsim.bw , 0.25 ) ));


zzsim.k0 = (zzsim.k0c / ( pow ( zzsim.bw , 0.25 ) ));


zzsim.rst = ((zzsim.ogr - (zzsim.k0 * zzsim.ast)) - (zzsim.ge * zzsim.ast));


zzsim.z99973 = zzsim.rst;


zzsim.rabsst = (zzsim.k0 * zzsim.ast);


zzsim.z99971 = zzsim.rabsst;


zzsim.rsi = (((zzsim.ge * zzsim.ast) - (zzsim.kabs * zzsim.asi)) - (zzsim.kunabs * zzsim.asi));


zzsim.z99969 = zzsim.rsi;


zzsim.rabssi = (zzsim.kabs * zzsim.asi);


zzsim.z99967 = zzsim.rabssi;


zzsim.kbile = (zzsim.kbilec * ( pow ( zzsim.bw , -(0.25) ) ));


zzsim.cl_bound = (zzsim.al_bound / zzsim.vl);


zzsim.cl_free = (zzsim.al_free / zzsim.vl);


zzsim.cvl = ((zzsim.cl_free / zzsim.pl) + zzsim.cl_bound);


zzsim.rl_free = (((((zzsim.ql * (zzsim.ca - zzsim.cvl)) * zzsim.free) - (zzsim.kbile * zzsim.al_free)) + ((zzsim.kabs * zzsim.asi) * zzsim.free)) + ((zzsim.k0 * zzsim.ast) * zzsim.free));


zzsim.z99961 = zzsim.rl_free;


zzsim.rfeces = ((zzsim.kbile * zzsim.al_free) + (zzsim.kunabs * zzsim.asi));


zzsim.z99965 = zzsim.rfeces;


zzsim.rl_bound = ((((zzsim.ql * (zzsim.ca - zzsim.cvl)) * (1 - zzsim.free)) + ((zzsim.kabs * zzsim.asi) * (1 - zzsim.free))) + ((zzsim.k0 * zzsim.ast) * (1 - zzsim.free)));


zzsim.z99963 = zzsim.rl_bound;


zzsim.rplas = ((((((zzsim.qr * zzsim.cvr) + (zzsim.qk * zzsim.cvk)) + (zzsim.ql * zzsim.cvl)) - (zzsim.qc * zzsim.ca)) + zzsim.ivr) + zzsim.raefflux);


zzsim.z99959 = zzsim.rplas;


zzsim.z99998 = 0.0;


zzsim.z99996 = 0.0;


zzsim.z99994 = 0.0;


zzsim.z99992 = 0.0;


zzsim.z99990 = 0.0;


zzsim.z99988 = 0.0;


zzsim.z99986 = 0.;


zzsim.z99984 = 0.;


zzsim.z99982 = 0.0;


zzsim.z99980 = 0.;


zzsim.z99978 = 0.;


zzsim.z99976 = 0.0;


zzsim.z99974 = 0.0;


zzsim.z99972 = 0.;


zzsim.z99970 = 0.;


zzsim.z99968 = 0.;


zzsim.z99966 = 0.;


zzsim.z99960 = 0.0;


zzsim.z99964 = 0.0;


zzsim.z99962 = 0.0;


zzsim.z99958 = 0.0;


zzsim.qbal = (zzsim.qc - ((zzsim.qk + zzsim.ql) + zzsim.qr));


zzsim.vbal = ((0.84 * zzsim.bw) - ((((((zzsim.vr + zzsim.vl) + zzsim.vkb) + zzsim.vptc) + zzsim.vfil) + zzsim.vplas) + zzsim.vk));


zzsim.ml = ((zzsim.mlc * zzsim.bw) * 1000);


zzsim.mptc = (zzsim.vptc * 1000);


zzsim.percentod_in_urine = ((zzsim.aurine / zzsim.odose) * 100);


zzsim.total_oral_uptake = (zzsim.aabssi + zzsim.aabsst);


zzsim.percentod_in_feces = ((zzsim.afeces / zzsim.odose) * 100);


zzsim.cl = ((zzsim.cl_free + zzsim.cl_bound) / zzsim.vl);


zzsim.abile = (zzsim.kbile * zzsim.al_free);


zzsim.amount_per_gram_liver = ((zzsim.al_free / zzsim.ml) * 1000);


zzsim.atissue = ((((((((((zzsim.aplas + zzsim.ar_free) + zzsim.ar_bound) + zzsim.akb_free) + zzsim.akb_bound) + zzsim.afil) + zzsim.aptc) + zzsim.al_free) + zzsim.al_bound) + zzsim.ast) + zzsim.asi);


zzsim.aloss = (zzsim.aurine + zzsim.afeces);


zzsim.atotal = (zzsim.atissue + zzsim.aloss);


break;


}

}
