<optstats type="sensitiv anal object">
  <runoptions mscriptpre="optimization.m" plotresults="True" />
  <coefficients>
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="bw" delta="0.003" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kurinec" delta="0.016" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kbilec" delta="4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="keffluxc" delta="0.1" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="k0c" delta="0.01" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="gec" delta="0.0054" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kunabs" delta="1E-06" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kabs" delta="0.03" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="kdif" delta="1E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pr" delta="0.0011" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pk" delta="0.0105" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="pl" delta="0.022" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="gfrc" delta="0.621" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="protein" delta="2E-08" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="rafapi" delta="0.000135" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="rafbaso" delta="0.000135" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="km_apical" delta="0.523" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="km_baso" delta="0.272" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vmax_apical_invitro" delta="93" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vmax_baso_invitro" delta="3.9345" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="free" delta="6E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mw" delta="4.1407" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vptcc" delta="1.35E-06" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vfilc" delta="8.4E-06" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vkc" delta="8.4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vlc" delta="0.00035" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="vplasc" delta="0.000312" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="htc" delta="0.0046" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qkc" delta="0.00141" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qlc" delta="0.00183" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="qcc" delta="0.14" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mlc" delta="0.00034" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
    <coefficient algorithm="Forward Difference" include="True" responsevarname="ca" parametername="mkc" delta="8.4E-05" normaltorespvar="True" normaltoparam="True" datacollectiontype="TimeSeries" />
  </coefficients>
</optstats>