
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <string>
#include "AcslSimRuntimeAPI.h"

void zzinitialize(unsigned long);
void zzsimulation(unsigned long);
void zzderivative(unsigned long, unsigned long);

typedef struct 
{
double t;
double aiv;
double aog;
double ar;
double akb;
double aptc;
double afil;
double aurine;
double agi;
double al;
double abound;
double afeces;
double aplas;
double z99999;
double z99997;
double z99995;
double z99993;
double z99991;
double z99989;
double z99987;
double z99985;
double z99983;
double z99981;
double z99979;
double z99977;
double z99998;
double z99996;
double z99994;
double z99992;
double z99990;
double z99988;
double z99986;
double z99984;
double z99982;
double z99980;
double z99978;
double z99976;
double tstart;
double bw;
double qcc;
double qlc;
double qkc;
double htc;
double vplasc;
double vlc;
double vkc;
double vfilc;
double mkc;
double free;
double vmax_basolateral;
double km_basolateral;
double vmax_apical;
double km_apical;
double gfrc;
double pl;
double pk;
double pr;
double kb;
double bmax;
double koff;
double kdif;
double kabs;
double kunabs;
double keffluxc;
double kbilec;
double kurinec;
double odosec;
double ogtime;
double ivdosec;
double ivtime;
double qc;
double qk;
double ql;
double qr;
double qbal;
double gfr;
double mk;
double vplas;
double vk;
double vkb;
double vfil;
double vl;
double vr;
double vptc;
double vbal;
double vptcc;
double kbile;
double kurine;
double kefflux;
double ivdose;
double ivr;
double ivon;
double odose;
double ogr;
double ogon;
double rr;
double ca;
double cvr;
double cr;
double rkb;
double cvk;
double ckb;
double cptc;
double rptc;
double cfil;
double rfil;
double rurine;
double rgi;
double rl;
double cvl;
double cl;
double rbound;
double altotal;
double cltotal;
double rfeces;
double rplas;
double atissue;
double aloss;
double atotal;
double tstop;
double cint;
long ialg;
long nstp;
double maxt;
double mint;
bool zzierr;
bool zzstopflag;
bool zzrnfl;
long zznist;
long zznblk;
bool zzfrfl;
bool zzjefl;
long zzndst;
long zzicon;
bool zzicfl;
long zznavr;
long zzinstidx;
bool zzstepstop;
long nciout;
long cioitg;
bool cjvitg;
double cssitg;
bool dpsitg;
bool ecsitg;
bool fdeitg;
long mxoitg;
bool nrwitg;
bool nxeitg;
double tjnitg;
bool tsmitg;
bool weditg;
bool wesitg;
bool wnditg;
bool wxditg;
bool cieitg;
long ubwitg;
long lbwitg;
long omfitg;
long cmd;
long dis;
long ndbug;
long plt;
long prn;
long malprn;
long rrr;
long save;
double zzticg;

} SimImpl;
SimImpl zzsim = 
{
0.0,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
0.0,
0.3,
14.0,
0.183,
0.141,
0.46,
0.0312,
0.035,
0.0084,
8.4e-4,
0.0084,
0.006,
1,
1,
1,
1,
62.1,
2.2,
1.05,
0.11,
1,
1,
1,
0.001,
31.3,
0.0001,
1.0,
0.35,
0.1,
10,
0.01,
0,
0.01,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
5.5555E+33,
24.0,
0.01,
5,
10,
1.0e9,
1.0e-9,
false,
false,
false,
2,
1,
false,
false,
0,
0,
false,
0,
0,
false,
1,
55555555,
true,
5.5555E+33,
true,
false,
false,
6,
false,
false,
0.2,
false,
true,
true,
false,
false,
true,
-1,
-1,
222,
4,
6,
0,
6,
9,
10,
8,
3,
0.0,

};

void AcslSimMain()
{

	AcslSimSetSystemInfo(167,// numSymbols
	12, // numOdeStates
	0, // numDaeStates
	0, // numDelayStates
	83,// numAlgebraicVars
	1, // numDerivativeSections
	0, // numDiscreteSections
	zzinitialize,
	zzsimulation,
	zzderivative,
	0);



#ifndef TRUE
  #define TRUE true
#endif
#ifndef FALSE
  #define FALSE false
#endif

AcslSimSetVariableDescriptor(1,"t",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_VARIABLE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(1,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(2,"aiv",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(2,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(3,"aog",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(3,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(4,"ar",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(4,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(5,"akb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(5,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(6,"aptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(6,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(7,"afil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(7,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(8,"aurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(8,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(9,"agi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(9,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(10,"al",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(10,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(11,"abound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(11,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(12,"afeces",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(12,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(13,"aplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_STATE,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(13,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(14,"z99999",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(14,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(15,"z99997",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(15,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(16,"z99995",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(16,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(17,"z99993",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(17,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(18,"z99991",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(18,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(19,"z99989",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(19,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(20,"z99987",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(20,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(21,"z99985",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(21,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(22,"z99983",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(22,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(23,"z99981",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(23,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(24,"z99979",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(24,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(25,"z99977",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_DERIV,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(25,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(26,"z99998",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(26,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(27,"z99996",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(27,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(28,"z99994",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(28,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(29,"z99992",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(29,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(30,"z99990",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(30,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(31,"z99988",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(31,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(32,"z99986",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(32,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(33,"z99984",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(33,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(34,"z99982",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(34,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(35,"z99980",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(35,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(36,"z99978",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(36,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(37,"z99976",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_INITCOND,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(37,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(38,"tstart",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(38,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(39,"bw",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(39,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(40,"qcc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(40,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(41,"qlc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(41,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(42,"qkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(42,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(43,"htc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(43,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(44,"vplasc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(44,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(45,"vlc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(45,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(46,"vkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(46,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(47,"vfilc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(47,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(48,"mkc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(48,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(49,"free",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(49,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(50,"vmax_basolateral",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(50,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(51,"km_basolateral",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(51,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(52,"vmax_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(52,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(53,"km_apical",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(53,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(54,"gfrc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(54,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(55,"pl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(55,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(56,"pk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(56,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(57,"pr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(57,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(58,"kb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(58,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(59,"bmax",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(59,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(60,"koff",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(60,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(61,"kdif",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(61,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(62,"kabs",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(62,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(63,"kunabs",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(63,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(64,"keffluxc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(64,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(65,"kbilec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(65,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(66,"kurinec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(66,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(67,"odosec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(67,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(68,"ogtime",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(68,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(69,"ivdosec",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(69,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(70,"ivtime",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(70,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(71,"qc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(71,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(72,"qk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(72,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(73,"ql",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(73,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(74,"qr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(74,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(75,"qbal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(75,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(76,"gfr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(76,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(77,"mk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(77,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(78,"vplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(78,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(79,"vk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(79,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(80,"vkb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(80,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(81,"vfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(81,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(82,"vl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(82,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(83,"vr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(83,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(84,"vptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(84,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(85,"vbal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(85,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(86,"vptcc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(86,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(87,"kbile",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(87,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(88,"kurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(88,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(89,"kefflux",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(89,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(90,"ivdose",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(90,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(91,"ivr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(91,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(92,"ivon",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(92,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(93,"odose",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(93,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(94,"ogr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(94,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(95,"ogon",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(95,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(96,"rr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(96,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(97,"ca",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(97,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(98,"cvr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(98,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(99,"cr",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(99,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(100,"rkb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(100,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(101,"cvk",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(101,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(102,"ckb",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(102,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(103,"cptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(103,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(104,"rptc",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(104,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(105,"cfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(105,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(106,"rfil",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(106,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(107,"rurine",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(107,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(108,"rgi",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(108,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(109,"rl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(109,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(110,"cvl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(110,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(111,"cl",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(111,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(112,"rbound",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(112,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(113,"altotal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(113,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(114,"cltotal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(114,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(115,"rfeces",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(115,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(116,"rplas",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(116,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(117,"atissue",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(117,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(118,"aloss",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(118,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(119,"atotal",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(119,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(120,"tstop",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ALGEBRAIC,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(120,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(121,"cint",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_CINTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(121,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(122,"ialg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ALGORITHM,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(122,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(123,"nstp",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_NSTEPS,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(123,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(124,"maxt",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_MAXTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(124,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(125,"mint",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_MINTERVAL,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(125,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(126,"zzierr",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ERRTAG,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(126,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(127,"zzstopflag",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(127,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(128,"zzrnfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(128,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(129,"zznist",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(129,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(130,"zznblk",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(130,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(131,"zzfrfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(131,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(132,"zzjefl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(132,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(133,"zzndst",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(133,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(134,"zzicon",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(134,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(135,"zzicfl",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(135,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(136,"zznavr",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(136,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(137,"zzinstidx",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(137,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(138,"zzstepstop",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_SYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(138,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(139,"nciout",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(139,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(140,"cioitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(140,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(141,"cjvitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(141,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(142,"cssitg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(142,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(143,"dpsitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(143,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(144,"ecsitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(144,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(145,"fdeitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(145,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(146,"mxoitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(146,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(147,"nrwitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(147,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(148,"nxeitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(148,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(149,"tjnitg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(149,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(150,"tsmitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(150,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(151,"weditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(151,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(152,"wesitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(152,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(153,"wnditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(153,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(154,"wxditg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(154,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(155,"cieitg",ACSL_DATATYPE_BOOLEAN,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(155,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(156,"ubwitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(156,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(157,"lbwitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(157,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(158,"omfitg",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(158,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(159,"cmd",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(159,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(160,"dis",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(160,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(161,"ndbug",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(161,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(162,"plt",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(162,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(163,"prn",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(163,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(164,"malprn",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(164,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(165,"rrr",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(165,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(166,"save",ACSL_DATATYPE_LONG,ACSL_SYMBOLTYPE_ACSLSYSTEMVAR,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(166,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

AcslSimSetVariableDescriptor(167,"zzticg",ACSL_DATATYPE_DOUBLE,ACSL_SYMBOLTYPE_VARIABLE_INIT,0,0,0,0,0,0,-1,-1);
AcslSimSetVariableExtendedInfo(167,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE, FALSE, 0, 0);

}

//******************************************************************************
void zzinitialize(unsigned long handle)
//******************************************************************************

{
AcslSimSetVariablePointer(handle,1,&zzsim.t);
AcslSimSetVariablePointer(handle,2,&zzsim.aiv);
AcslSimSetVariablePointer(handle,3,&zzsim.aog);
AcslSimSetVariablePointer(handle,4,&zzsim.ar);
AcslSimSetVariablePointer(handle,5,&zzsim.akb);
AcslSimSetVariablePointer(handle,6,&zzsim.aptc);
AcslSimSetVariablePointer(handle,7,&zzsim.afil);
AcslSimSetVariablePointer(handle,8,&zzsim.aurine);
AcslSimSetVariablePointer(handle,9,&zzsim.agi);
AcslSimSetVariablePointer(handle,10,&zzsim.al);
AcslSimSetVariablePointer(handle,11,&zzsim.abound);
AcslSimSetVariablePointer(handle,12,&zzsim.afeces);
AcslSimSetVariablePointer(handle,13,&zzsim.aplas);
AcslSimSetVariablePointer(handle,14,&zzsim.z99999);
AcslSimSetVariablePointer(handle,15,&zzsim.z99997);
AcslSimSetVariablePointer(handle,16,&zzsim.z99995);
AcslSimSetVariablePointer(handle,17,&zzsim.z99993);
AcslSimSetVariablePointer(handle,18,&zzsim.z99991);
AcslSimSetVariablePointer(handle,19,&zzsim.z99989);
AcslSimSetVariablePointer(handle,20,&zzsim.z99987);
AcslSimSetVariablePointer(handle,21,&zzsim.z99985);
AcslSimSetVariablePointer(handle,22,&zzsim.z99983);
AcslSimSetVariablePointer(handle,23,&zzsim.z99981);
AcslSimSetVariablePointer(handle,24,&zzsim.z99979);
AcslSimSetVariablePointer(handle,25,&zzsim.z99977);
AcslSimSetVariablePointer(handle,26,&zzsim.z99998);
AcslSimSetVariablePointer(handle,27,&zzsim.z99996);
AcslSimSetVariablePointer(handle,28,&zzsim.z99994);
AcslSimSetVariablePointer(handle,29,&zzsim.z99992);
AcslSimSetVariablePointer(handle,30,&zzsim.z99990);
AcslSimSetVariablePointer(handle,31,&zzsim.z99988);
AcslSimSetVariablePointer(handle,32,&zzsim.z99986);
AcslSimSetVariablePointer(handle,33,&zzsim.z99984);
AcslSimSetVariablePointer(handle,34,&zzsim.z99982);
AcslSimSetVariablePointer(handle,35,&zzsim.z99980);
AcslSimSetVariablePointer(handle,36,&zzsim.z99978);
AcslSimSetVariablePointer(handle,37,&zzsim.z99976);
AcslSimSetVariablePointer(handle,38,&zzsim.tstart);
AcslSimSetVariablePointer(handle,39,&zzsim.bw);
AcslSimSetVariablePointer(handle,40,&zzsim.qcc);
AcslSimSetVariablePointer(handle,41,&zzsim.qlc);
AcslSimSetVariablePointer(handle,42,&zzsim.qkc);
AcslSimSetVariablePointer(handle,43,&zzsim.htc);
AcslSimSetVariablePointer(handle,44,&zzsim.vplasc);
AcslSimSetVariablePointer(handle,45,&zzsim.vlc);
AcslSimSetVariablePointer(handle,46,&zzsim.vkc);
AcslSimSetVariablePointer(handle,47,&zzsim.vfilc);
AcslSimSetVariablePointer(handle,48,&zzsim.mkc);
AcslSimSetVariablePointer(handle,49,&zzsim.free);
AcslSimSetVariablePointer(handle,50,&zzsim.vmax_basolateral);
AcslSimSetVariablePointer(handle,51,&zzsim.km_basolateral);
AcslSimSetVariablePointer(handle,52,&zzsim.vmax_apical);
AcslSimSetVariablePointer(handle,53,&zzsim.km_apical);
AcslSimSetVariablePointer(handle,54,&zzsim.gfrc);
AcslSimSetVariablePointer(handle,55,&zzsim.pl);
AcslSimSetVariablePointer(handle,56,&zzsim.pk);
AcslSimSetVariablePointer(handle,57,&zzsim.pr);
AcslSimSetVariablePointer(handle,58,&zzsim.kb);
AcslSimSetVariablePointer(handle,59,&zzsim.bmax);
AcslSimSetVariablePointer(handle,60,&zzsim.koff);
AcslSimSetVariablePointer(handle,61,&zzsim.kdif);
AcslSimSetVariablePointer(handle,62,&zzsim.kabs);
AcslSimSetVariablePointer(handle,63,&zzsim.kunabs);
AcslSimSetVariablePointer(handle,64,&zzsim.keffluxc);
AcslSimSetVariablePointer(handle,65,&zzsim.kbilec);
AcslSimSetVariablePointer(handle,66,&zzsim.kurinec);
AcslSimSetVariablePointer(handle,67,&zzsim.odosec);
AcslSimSetVariablePointer(handle,68,&zzsim.ogtime);
AcslSimSetVariablePointer(handle,69,&zzsim.ivdosec);
AcslSimSetVariablePointer(handle,70,&zzsim.ivtime);
AcslSimSetVariablePointer(handle,71,&zzsim.qc);
AcslSimSetVariablePointer(handle,72,&zzsim.qk);
AcslSimSetVariablePointer(handle,73,&zzsim.ql);
AcslSimSetVariablePointer(handle,74,&zzsim.qr);
AcslSimSetVariablePointer(handle,75,&zzsim.qbal);
AcslSimSetVariablePointer(handle,76,&zzsim.gfr);
AcslSimSetVariablePointer(handle,77,&zzsim.mk);
AcslSimSetVariablePointer(handle,78,&zzsim.vplas);
AcslSimSetVariablePointer(handle,79,&zzsim.vk);
AcslSimSetVariablePointer(handle,80,&zzsim.vkb);
AcslSimSetVariablePointer(handle,81,&zzsim.vfil);
AcslSimSetVariablePointer(handle,82,&zzsim.vl);
AcslSimSetVariablePointer(handle,83,&zzsim.vr);
AcslSimSetVariablePointer(handle,84,&zzsim.vptc);
AcslSimSetVariablePointer(handle,85,&zzsim.vbal);
AcslSimSetVariablePointer(handle,86,&zzsim.vptcc);
AcslSimSetVariablePointer(handle,87,&zzsim.kbile);
AcslSimSetVariablePointer(handle,88,&zzsim.kurine);
AcslSimSetVariablePointer(handle,89,&zzsim.kefflux);
AcslSimSetVariablePointer(handle,90,&zzsim.ivdose);
AcslSimSetVariablePointer(handle,91,&zzsim.ivr);
AcslSimSetVariablePointer(handle,92,&zzsim.ivon);
AcslSimSetVariablePointer(handle,93,&zzsim.odose);
AcslSimSetVariablePointer(handle,94,&zzsim.ogr);
AcslSimSetVariablePointer(handle,95,&zzsim.ogon);
AcslSimSetVariablePointer(handle,96,&zzsim.rr);
AcslSimSetVariablePointer(handle,97,&zzsim.ca);
AcslSimSetVariablePointer(handle,98,&zzsim.cvr);
AcslSimSetVariablePointer(handle,99,&zzsim.cr);
AcslSimSetVariablePointer(handle,100,&zzsim.rkb);
AcslSimSetVariablePointer(handle,101,&zzsim.cvk);
AcslSimSetVariablePointer(handle,102,&zzsim.ckb);
AcslSimSetVariablePointer(handle,103,&zzsim.cptc);
AcslSimSetVariablePointer(handle,104,&zzsim.rptc);
AcslSimSetVariablePointer(handle,105,&zzsim.cfil);
AcslSimSetVariablePointer(handle,106,&zzsim.rfil);
AcslSimSetVariablePointer(handle,107,&zzsim.rurine);
AcslSimSetVariablePointer(handle,108,&zzsim.rgi);
AcslSimSetVariablePointer(handle,109,&zzsim.rl);
AcslSimSetVariablePointer(handle,110,&zzsim.cvl);
AcslSimSetVariablePointer(handle,111,&zzsim.cl);
AcslSimSetVariablePointer(handle,112,&zzsim.rbound);
AcslSimSetVariablePointer(handle,113,&zzsim.altotal);
AcslSimSetVariablePointer(handle,114,&zzsim.cltotal);
AcslSimSetVariablePointer(handle,115,&zzsim.rfeces);
AcslSimSetVariablePointer(handle,116,&zzsim.rplas);
AcslSimSetVariablePointer(handle,117,&zzsim.atissue);
AcslSimSetVariablePointer(handle,118,&zzsim.aloss);
AcslSimSetVariablePointer(handle,119,&zzsim.atotal);
AcslSimSetVariablePointer(handle,120,&zzsim.tstop);
AcslSimSetVariablePointer(handle,121,&zzsim.cint);
AcslSimSetVariablePointer(handle,122,&zzsim.ialg);
AcslSimSetVariablePointer(handle,123,&zzsim.nstp);
AcslSimSetVariablePointer(handle,124,&zzsim.maxt);
AcslSimSetVariablePointer(handle,125,&zzsim.mint);
AcslSimSetVariablePointer(handle,126,&zzsim.zzierr);
AcslSimSetVariablePointer(handle,127,&zzsim.zzstopflag);
AcslSimSetVariablePointer(handle,128,&zzsim.zzrnfl);
AcslSimSetVariablePointer(handle,129,&zzsim.zznist);
AcslSimSetVariablePointer(handle,130,&zzsim.zznblk);
AcslSimSetVariablePointer(handle,131,&zzsim.zzfrfl);
AcslSimSetVariablePointer(handle,132,&zzsim.zzjefl);
AcslSimSetVariablePointer(handle,133,&zzsim.zzndst);
AcslSimSetVariablePointer(handle,134,&zzsim.zzicon);
AcslSimSetVariablePointer(handle,135,&zzsim.zzicfl);
AcslSimSetVariablePointer(handle,136,&zzsim.zznavr);
AcslSimSetVariablePointer(handle,137,&zzsim.zzinstidx);
AcslSimSetVariablePointer(handle,138,&zzsim.zzstepstop);
AcslSimSetVariablePointer(handle,139,&zzsim.nciout);
AcslSimSetVariablePointer(handle,140,&zzsim.cioitg);
AcslSimSetVariablePointer(handle,141,&zzsim.cjvitg);
AcslSimSetVariablePointer(handle,142,&zzsim.cssitg);
AcslSimSetVariablePointer(handle,143,&zzsim.dpsitg);
AcslSimSetVariablePointer(handle,144,&zzsim.ecsitg);
AcslSimSetVariablePointer(handle,145,&zzsim.fdeitg);
AcslSimSetVariablePointer(handle,146,&zzsim.mxoitg);
AcslSimSetVariablePointer(handle,147,&zzsim.nrwitg);
AcslSimSetVariablePointer(handle,148,&zzsim.nxeitg);
AcslSimSetVariablePointer(handle,149,&zzsim.tjnitg);
AcslSimSetVariablePointer(handle,150,&zzsim.tsmitg);
AcslSimSetVariablePointer(handle,151,&zzsim.weditg);
AcslSimSetVariablePointer(handle,152,&zzsim.wesitg);
AcslSimSetVariablePointer(handle,153,&zzsim.wnditg);
AcslSimSetVariablePointer(handle,154,&zzsim.wxditg);
AcslSimSetVariablePointer(handle,155,&zzsim.cieitg);
AcslSimSetVariablePointer(handle,156,&zzsim.ubwitg);
AcslSimSetVariablePointer(handle,157,&zzsim.lbwitg);
AcslSimSetVariablePointer(handle,158,&zzsim.omfitg);
AcslSimSetVariablePointer(handle,159,&zzsim.cmd);
AcslSimSetVariablePointer(handle,160,&zzsim.dis);
AcslSimSetVariablePointer(handle,161,&zzsim.ndbug);
AcslSimSetVariablePointer(handle,162,&zzsim.plt);
AcslSimSetVariablePointer(handle,163,&zzsim.prn);
AcslSimSetVariablePointer(handle,164,&zzsim.malprn);
AcslSimSetVariablePointer(handle,165,&zzsim.rrr);
AcslSimSetVariablePointer(handle,166,&zzsim.save);
AcslSimSetVariablePointer(handle,167,&zzsim.zzticg);

zzsim.zzinstidx = handle;
}

//******************************************************************************
void zzsimulation(unsigned long handle)
//******************************************************************************

{
   if(zzsim.zzicon == false)
   {
      zznits(handle, "");




 
      zzrset(handle);
   }

   while(zzsim.zzstopflag == false && zzsim.zzstepstop == false)
   {



if((zzsim.t >= zzsim.tstop))
{

zztrmt(zzsim.zzinstidx,"checked on communication interval: REACHED TSTOP")
;

}

   

      AcslSimIntegrate(handle);
   }

   if(zzsim.zzstepstop == false)
   {
   


   

   }
}

//******************************************************************************
void zzderivative(unsigned long handle, unsigned long section)
//******************************************************************************

{

switch(section) 
{
   case 0: /* Initial */


			
		      
   break;
   case 1: /* Terminal */


			
		   
   break;
case 2: /* Dynamic */


			
		   
   break;
case 3: /* Left over code, executed once */


  
   
   break;


   /* Derivative */
			

case 500:


zzsim.ivdose = (zzsim.ivdosec * zzsim.bw);


zzsim.ivon = rsw((zzsim.t >= zzsim.ivtime),0.,1.);


zzsim.ivr = ((zzsim.ivon * zzsim.ivdose) / zzsim.ivtime);


zzsim.z99999 = zzsim.ivr;


zzsim.odose = (zzsim.odosec * zzsim.bw);


zzsim.ogon = rsw((zzsim.t >= zzsim.ogtime),0.,1.);


zzsim.ogr = ((zzsim.ogon * zzsim.odose) / zzsim.ogtime);


zzsim.z99997 = zzsim.ogr;


zzsim.qc = ((zzsim.qcc * ( pow ( zzsim.bw , 0.75 ) )) * (1 - zzsim.htc));


zzsim.qk = (zzsim.qkc * zzsim.qc);


zzsim.ql = (zzsim.qlc * zzsim.qc);


zzsim.qr = ((zzsim.qc - zzsim.qk) - zzsim.ql);


zzsim.vplas = (zzsim.vplasc * zzsim.bw);


zzsim.ca = (zzsim.aplas / zzsim.vplas);


zzsim.vk = (zzsim.vkc * zzsim.bw);


zzsim.vkb = (zzsim.vk * 0.16);


zzsim.vfil = (zzsim.vfilc * zzsim.bw);


zzsim.vl = (zzsim.vlc * zzsim.bw);


zzsim.mk = ((zzsim.mkc * zzsim.bw) * 1000);


zzsim.vptcc = (6.0e7 * 2.25e-12);


zzsim.vptc = (zzsim.mk * zzsim.vptcc);


zzsim.vr = (((((((0.84 * zzsim.bw) - zzsim.vplas) - zzsim.vkb) - zzsim.vptc) - zzsim.vfil) - zzsim.vl) - zzsim.vk);


zzsim.cr = (zzsim.ar / zzsim.vr);


zzsim.cvr = (zzsim.cr / zzsim.pr);


zzsim.rr = ((zzsim.qr * (zzsim.ca - zzsim.cvr)) * zzsim.free);


zzsim.z99995 = zzsim.rr;


zzsim.gfr = (zzsim.gfrc * (zzsim.mk / 1000));


zzsim.ckb = (zzsim.akb / zzsim.vkb);


zzsim.cvk = (zzsim.ckb / zzsim.pk);


zzsim.cptc = (zzsim.aptc / zzsim.vptc);


zzsim.rkb = ((((((zzsim.qk * (zzsim.ca - zzsim.cvk)) * zzsim.free) - (zzsim.ca * zzsim.gfr)) - ((zzsim.vmax_basolateral * zzsim.ckb) / (zzsim.km_basolateral + zzsim.ckb))) + (zzsim.kdif * zzsim.cptc)) - (zzsim.kdif * zzsim.ckb));


zzsim.z99993 = zzsim.rkb;


zzsim.kefflux = (zzsim.keffluxc * ( pow ( zzsim.bw , 0.75 ) ));


zzsim.cfil = (zzsim.afil / zzsim.vfil);


zzsim.rptc = ((((((zzsim.vmax_basolateral * zzsim.ckb) / (zzsim.km_basolateral + zzsim.ckb)) + ((zzsim.vmax_apical * zzsim.cfil) / (zzsim.km_apical + zzsim.cfil))) - (zzsim.kefflux * zzsim.cptc)) - (zzsim.kdif * zzsim.cptc)) + (zzsim.kdif * zzsim.ckb));


zzsim.z99991 = zzsim.rptc;


zzsim.kurine = (zzsim.kurinec * ( pow ( zzsim.bw , -(0.25) ) ));


zzsim.rfil = (((zzsim.ca * zzsim.gfr) - ((zzsim.vmax_apical * zzsim.cfil) / (zzsim.km_apical + zzsim.cfil))) - (zzsim.afil * zzsim.kurine));


zzsim.z99989 = zzsim.rfil;


zzsim.rurine = (zzsim.kurine * zzsim.afil);


zzsim.z99987 = zzsim.rurine;


zzsim.rgi = (((-(zzsim.kabs) * zzsim.agi) + zzsim.ogr) - (zzsim.kunabs * zzsim.agi));


zzsim.z99985 = zzsim.rgi;


zzsim.kbile = (zzsim.kbilec * ( pow ( zzsim.bw , -(0.25) ) ));


zzsim.cl = (zzsim.al / zzsim.vl);


zzsim.cvl = (zzsim.cl / zzsim.pl);


zzsim.rl = ((((((zzsim.ql * (zzsim.ca - zzsim.cvl)) * zzsim.free) + (zzsim.kabs * zzsim.agi)) - (zzsim.kbile * zzsim.al)) - ((zzsim.bmax * zzsim.cl) / (zzsim.kb + zzsim.cl))) + (zzsim.koff * zzsim.abound));


zzsim.z99983 = zzsim.rl;


zzsim.rbound = (((zzsim.bmax * zzsim.cl) / (zzsim.kb + zzsim.cl)) - (zzsim.koff * zzsim.abound));


zzsim.z99981 = zzsim.rbound;


zzsim.rfeces = ((zzsim.kunabs * zzsim.agi) + (zzsim.kbile * zzsim.al));


zzsim.z99979 = zzsim.rfeces;


zzsim.rplas = (((((((zzsim.qr * zzsim.cvr) * zzsim.free) + ((zzsim.qk * zzsim.cvk) * zzsim.free)) + ((zzsim.ql * zzsim.cvl) * zzsim.free)) - ((zzsim.qc * zzsim.ca) * zzsim.free)) + zzsim.ivr) + (zzsim.kefflux * zzsim.cptc));


zzsim.z99977 = zzsim.rplas;


zzsim.z99998 = 0.0;


zzsim.z99996 = 0.0;


zzsim.z99994 = 0.0;


zzsim.z99992 = 0.0;


zzsim.z99990 = 0.0;


zzsim.z99988 = 0.0;


zzsim.z99986 = 0.0;


zzsim.z99984 = 0.0;


zzsim.z99982 = 0.0;


zzsim.z99980 = 0.0;


zzsim.z99978 = 0.0;


zzsim.z99976 = 0.0;


zzsim.qbal = (zzsim.qc - ((zzsim.qk + zzsim.ql) + zzsim.qr));


zzsim.vbal = ((0.84 * zzsim.bw) - ((((((zzsim.vr + zzsim.vl) + zzsim.vkb) + zzsim.vptc) + zzsim.vfil) + zzsim.vplas) + zzsim.vk));


zzsim.altotal = (zzsim.al + zzsim.abound);


zzsim.cltotal = (zzsim.altotal / zzsim.vl);


zzsim.atissue = ((((((zzsim.aplas + zzsim.ar) + zzsim.aptc) + zzsim.akb) + zzsim.afil) + zzsim.altotal) + zzsim.agi);


zzsim.aloss = (zzsim.aurine + zzsim.afeces);


zzsim.atotal = (zzsim.atissue + zzsim.aloss);


break;


}

}
